apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

bases:
  - ../../base

patchesJson6902:
  - target:
      group: noobaa.io
      version: v1alpha1
      kind: BackingStore
      name: mcg-pv-pool-bs
      namespace: openshift-storage
    path: patch-storage-capacity.yaml