---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-data-foundation-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-config/openshift-data-foundation-operator/operator/overlays/stable-4.16
    repoURL:  https://gitlab.apps.cluster-hzjdg.hzjdg.sandbox2168.opentlc.com/user1/quarkus-microservices-kustomize-openshift-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
