---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservice-demo

resources:
  - namespace.yaml
  - service-a-deployment.yaml
  - service-a-service.yaml
  - pull-secret.yaml

patchesStrategicMerge:
  - patch-image.yaml
  - patch-pull-secret.yaml
