---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservice-demo

resources:
  - service-b-deployment.yaml
  - service-b-service.yaml
  - service-b-route.yaml

patchesStrategicMerge:
  - patch-image.yaml
